### ISSUE TITLE
Firefox-specific code

### ISSUE THREAD

**Issue by dvalter** [OhMyGuus/I-Dont-Care-About-Cookies#12]
Upstream IDCAC code has a number of Firefox-specific features/hacks. They may (or may not) affect on quality of FF support, so they may need a closer look.

I've uploaded FF sources [here](https://github.com/dvalter/IDCAC_uo_mirror_firefox) and v3.4.3 diff [here](https://gist.github.com/dvalter/fa123bcaca278a8bb6de575d2c22c97e)

**Comment by OhMyGuus** [comment]
Oh very interesting, thanks :)

**Comment by OhMyGuus** [comment]
Will close this issue now since most of the code has been implemented now (except the notifications part but I'm going to rewrite that)
