### ISSUE TITLE
[REQ] Website request: https://refresher.cz/

### ISSUE THREAD

**Issue by BeanGreen247** [OhMyGuus/I-Dont-Care-About-Cookies#149]
**Website URL(s)**

- refresher.cz

**Browser**
[X] Firefox
[] Chrome

**Extension version**
V1.0.0

**Comment by OhMyGuus** [comment]
Seems to work fine for me, is there something else wrong?

**Comment by BeanGreen247** [comment]
Hi seems to be working fine now. Issue can be closed. Thanks
