### ISSUE TITLE
Item about the Extension Author

### ISSUE THREAD

**Issue by Erghel** [OhMyGuus/I-Dont-Care-About-Cookies#18]
In the extension's manifest in the Author - the author is the old developer. Will this be changed in the future, and if so, how? Is it possible to change it now?

**Comment by Erghel** [comment]
It might look something like this:
```json
"author": "OhMyGuus and Community (ex-Daniel Kladnik)"
```

**Comment by totoroot** [comment]
@Erghel Can this issue be closed now that your suggested changes got implemented?
