### ISSUE TITLE
Golem.de

### ISSUE THREAD

**Issue by merj1928** [OhMyGuus/I-Dont-Care-About-Cookies#22]
I must click the cookie banner.

**Comment by OhMyGuus** [comment]
Website uses a server-side redirect for the cookie-banners 

Cookies required to set by extension to disable this: 

key: golem_consent20
value: cmp|220101

Optional cookies: 
key: _sp_enable_dfp_personalized_ads
value: false

key: golem_allow_embedd 
value: false

**Comment by HolgerAusB** [comment]
I tried this several times with fenced/containeres tabs. Four of five times the consent banner was automatically clicked away within 2 seconds. Only at my second try, the banner persists. (the coockie will accepted or you have to pay for the content)

**Comment by OhMyGuus** [comment]
> I tried this several times with fenced/containered tabs. Four of five times the consent banner was automatically clicked away within 2 seconds. Only at my second try, the banner persists. (the cookie will accepted or you have to pay for the content)

Oh indeed you are right, I have no idea yet why it stopped working for a second for me as well, it should look for the 
.sp_choice_type_11 element and click on it. 
For some reason it sometimes bugs out on this site will look into it (and maybe change it to the cookie method) 👍

**Comment by OhMyGuus** [comment]
This should be fixed now on v1.0.2 this was a bug with the firefox support.
