### ISSUE TITLE
the Guardian

### ISSUE THREAD

**Issue by doodahjones** [OhMyGuus/I-Dont-Care-About-Cookies#28]
still gives an annoying popup about cookies etc

**Comment by winskil** [comment]
Can't seem to replicate this behaviour.
What browser are you running?
What version of the extension are you running? 
On Firefox you can check the version by going to `about:addons` and clicking the extension name
<img width="668" alt="image" src="https://user-images.githubusercontent.com/44670482/192122402-18273d63-4c54-40c8-ab80-f3d0f1ac9a23.png">
On Chrome by going to `chrome://extensions/`
<img width="397" alt="image" src="https://user-images.githubusercontent.com/44670482/192122494-a5ebbf15-a59d-48e6-89d7-3151a48c2d67.png">

**Comment by OhMyGuus** [comment]
Should be fixed in latest release
