### ISSUE TITLE
Chrome Store stuck on 1.0.6

### ISSUE THREAD

**Issue by bwims** [OhMyGuus/I-Dont-Care-About-Cookies#283]
Hi,

I'm subscribed to your release announcements and just thought I'd let you know that although the recommendation is to use the Chrome extension store, the version there seems to be stuck at 1.0.6

Thanks for all your efforts!

**Comment by jniggemann** [comment]
Can confirm, bbserved at when v 1.0.7 came out. It's still on 1.0.6 for me, too.

**Comment by OhMyGuus** [comment]
We are aware that chrome is still 2 versions behind, since 1.0.7 was just a bugfix for Firefox so I never uploaded that one to the Chrome webstore.
However for 1.0.8 they are still reviewing it which can take a day or two on the Chrome webstore.

Still thanks for letting us know 😄

**Comment by OhMyGuus** [comment]
Update 1.0.8 is live on the chrome web store :😁
