### ISSUE TITLE
zeit.de Cookie Warning

### ISSUE THREAD

**Issue by andreas-2017** [OhMyGuus/I-Dont-Care-About-Cookies#29]
The cookie warning window was not clicked automatically.

https://www.zeit.de/

**Comment by OhMyGuus** [comment]
Thanks for the report!

-- Info for me --
cookie way: 
_sp_enable_dfp_personalized_ads -> false
zonconsent -> 2022-09-26T13:01:08.740Z (timestamp)

click way: 
message-component message-button no-children focusable sp_choice_type_11
