### ISSUE TITLE
zip file seems to be corrupted

### ISSUE THREAD

**Issue by felixZmn** [OhMyGuus/I-Dont-Care-About-Cookies#3]
The installation in Firefox fails with the error Message “This add-on could not be installed because it appears to be corrupt”. In Chrome, the zip can be installed, but there is a deprecation warning for manifest version 2.

**Comment by Avtpp** [comment]
> The installation in Firefox fails with the error Message “This add-on could not be installed because it appears to be corrupt”. In Chrome, the zip can be installed, but there is a deprecation warning for manifest version 2.

Same error message for me on Librewolf (Firefox).

**Comment by winskil** [comment]
Ran the source code through https://addons.mozilla.org/en-GB/developers/addon/submit/distribution and it created an XPI file which works.

**Comment by DAC324** [comment]
> Ran the source code through https://addons.mozilla.org/en-GB/developers/addon/submit/distribution and it created an XPI file which works. So it needs to be signed in order to work.

Can you explain which steps are required to create that working XPI file?

**Comment by winskil** [comment]
> > Ran the source code through https://addons.mozilla.org/en-GB/developers/addon/submit/distribution and it created an XPI file which works. So it needs to be signed in order to work.
> 
> Can you explain which steps are required to create that working XPI file?

I just logged into the developer hub, clicked on `Submit new extension` and followed the instructions.
I creates the signed extension in a few minutes.

**Comment by DAC324** [comment]
> I just logged into the developer hub, clicked on `Submit new extension` and followed the instructions.
> It creates the signed extension in a few minutes.

This does not seem to work for me. I uploaded IDAC.zip "for my own", it validates OK but then I am presented with the following:
```

Submit a New Add-on
Do You Need to Submit Source Code?

Mozilla’s add-on reviewers need to be able to read and reproduce the code in your extension. If they can’t, your extension may be rejected.

Do you use any of the following in your extension?

    Code generators or minifiers
    Tools that combine multiple files into a single file, such as webpack
    Web template engines, both for HTML and CSS
    Any other tool that takes code or files, applies processing, and generates code or file(s) to include in the extension

Yes No
```
What am I supposed to do here?

**Comment by OhMyGuus** [comment]
- 1) Already working on migrating the Manifest from V2 to Manifest V3, still need some testing for it but should be working soon. 
- 2) Thanks for the report, I didn't have time yesterday anymore to test it on firefox but going to do that now and see if I can update the action to generate the XPI archive as well.

**Comment by winskil** [comment]
@DAC324 
![Screenshot 2022-09-16 at 14 24 42](https://user-images.githubusercontent.com/44670482/190628518-3b0cc443-10f9-4b9e-adce-a99acaa1ad62.png)
![Screenshot 2022-09-16 at 14 23 52](https://user-images.githubusercontent.com/44670482/190628529-a4eb42ce-a043-4a00-a469-022ecc188599.png)

**Comment by Hermit8947** [comment]
> * 1. Already working on migrating the Manifest from V2 to Manifest V3, still need some testing for it but should be working soon.
> 
>     * 2. Thanks for the report, I didn't have time yesterday anymore to test it on firefox but going to do that now and see if I can update the action to generate the XPI archive as well.

thx, for your work, mate!

**Comment by DAC324** [comment]
For all those who do not have a Firefox account:
https://userupload.net/t5oi2ir03szm

**Comment by OhMyGuus** [comment]
https://github.com/OhMyGuus/I-Dont-Care-About-Cookies/releases/tag/IDCAC_2022.09.16_15_00
The latest release has now a working  IDCAC_firefox.xpi
