### ISSUE TITLE
Imposter repackaged and sells the add-on on Chrome store

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [OhMyGuus/I-Dont-Care-About-Cookies#301]
Someone has taken this add-on, added in-app purchases, slightly changed the name (Still Don't Care about Cookies) and picked a similar looking icon:
https://chrome.google.com/webstore/detail/still-dont-care-about-coo/fmmjjgjhblhocbmigepoobidbbcknjkf

He even registered a website: https://www.stilldontcareaboutcookies.com/

If I was a Chrome user, he could have fooled me.
I got that link from a [ghacks article](https://www.ghacks.net/2022/09/15/avast-acquires-i-dont-care-about-cookies-browser-extension/) about the Avast acquisition.

**Comment by nicolaasjan** [comment]
Already reported [here](https://github.com/OhMyGuus/I-Dont-Care-About-Cookies/issues/55). 🙂
See also the announcement [here](https://github.com/OhMyGuus/I-Dont-Care-About-Cookies/discussions/49).
