### ISSUE TITLE
Will it update automatically?

### ISSUE THREAD

**Issue by M1Aston** [OhMyGuus/I-Dont-Care-About-Cookies#31]
Once installed manually, will  this receive automatic updates?

**Comment by arjun44** [comment]
Has it been published to AMO and CWS (chrome web store)?

**Comment by OhMyGuus** [comment]
> Has it been published to AMO and CWS (chrome web store)?

V1.0.0 has been published & is live on the chrome webstore at the moment. 
I uploaded V1.0.3 today to AMO & CWS  (6 hours ago) as well but it's still under review.

**Comment by OhMyGuus** [comment]
[Firefox browser add-ons](https://addons.mozilla.org/en-US/firefox/addon/istilldontcareaboutcookies/
)
[Chrome Web Store](https://chrome.google.com/webstore/detail/i-still-dont-care-about-c/edibdbjcniadpccecjdfdjjppcpchdlm)
 _(The chrome webstore version is still outdated to v1.0.0 but will be updates soon to v1.0.3 (with the fixes on the store page after review))_
