### ISSUE TITLE
Lots of newspapers

### ISSUE THREAD

**Issue by M1Aston** [OhMyGuus/I-Dont-Care-About-Cookies#32]
belonging to a single company with the same cookie messages.

https://www.ad.nl/
https://www.bndestem.nl
http://www.destentor.nl/
http://www.gelderlander.nl/
etc., etc...

**Comment by OhMyGuus** [comment]
What browser are u using, just to see if I can see why it is showing those messages

**Comment by M1Aston** [comment]
Correct, Firefox
A word of warning. I have seen quite a few problems (no video playback, embedded social media elements being blocked) with other cookie managers in the past. I don't know, but it looks like some cookie elements need to be allowed for everything to work normally.

**Comment by OhMyGuus** [comment]
> Correct, Firefox A word of warning. I have seen quite a few problems (no video playback, embedded social media elements being blocked) with other cookie managers in the past. I don't know, but it looks like some cookie elements need to be allowed for everything to work normally.

I've noticed that as well with some media like with media from RTL before, I will put this into my look into list 👍

**Comment by OhMyGuus** [comment]
Should be fixed in latest release.

**Comment by M1Aston** [comment]
Everything is working well so far. Brilliant. :-)
Thanks a lot.

**Comment by nicolaasjan** [comment]
> Should be fixed in latest release.

I had to disable the extension on https://www.gelderlander.nl/ to let video play on Chromium.
On Firefox even that didn't work...

**Comment by OhMyGuus** [comment]
I created a new issue for the video playback #46 and will close this one since the base issue seems to be fixed
