### ISSUE TITLE
Chromium complains about Manifest version 2 being deprecated

### ISSUE THREAD

**Issue by DAC324** [OhMyGuus/I-Dont-Care-About-Cookies#4]
Hello,

I was able to install the zip file in Chromium on Linux as per instructions. Just open Settings, Extensions and drag and drop the zip file on it.
However, Chromium complains about Manifest version 2 being deprecated. 
Is there something that could be done about that?

Kind regards.

**Comment by OhMyGuus** [comment]
I'm already working on migrating it to Manifest V3 which is also required to publish it. Should be finished soon :)

**Comment by marcoclg19** [comment]
> I'm already working on migrating it to Manifest V3 which is also required to publish it. Should be finished soon :)

Hi, so if I download the extension from the chrome webstore now, is it already compatible with MV3?
