### ISSUE TITLE
[REQ] Website request: https://shop.lmvz.ch/

### ISSUE THREAD

**Issue by mowgli** [OhMyGuus/I-Dont-Care-About-Cookies#42]
**Website URL(s)**
- https://shop.lmvz.ch/

**Browser**
[x] Firefox
[ ] Chrome

**Extension version**
V3.4.3

**Comment by OhMyGuus** [comment]
Thanks for the repot!

-- Info about fixing this in the extension for me --
class: opc-manager-cookie

**Comment by OhMyGuus** [comment]
Should be fixed with PR #45
