### ISSUE TITLE
Allow access to file URLs and Collect errors turned on

### ISSUE THREAD

**Issue by Veriiix** [OhMyGuus/I-Dont-Care-About-Cookies#43]
I just wondered why *Allow access to file URLs* and *Collect errors* is automatically turned on in the Chrome version. Why does the extension need these permissions or is it not possible to disable them in advance?

**Comment by OhMyGuus** [comment]
Good question I throught that those permissions where removed in v1.0.2. Will look into it, thanks for the report!

**Comment by OhMyGuus** [comment]
Looked into it and it seems to be default by chrome if u load an unpacked extension. 
We can't change that but I might add it to the install guide, we also will be on the webstore itself soon (its under review at the moment).
