### ISSUE TITLE
[BUG] Video playback on certain websites

### ISSUE THREAD

**Issue by OhMyGuus** [OhMyGuus/I-Dont-Care-About-Cookies#46]
I have noticed before that there are some video playback on certain websites so I need to look into this. 

If someone has examples that I can look into that would be nice :)

**Comment by nicolaasjan** [comment]
> If someone has examples that I can look into that would be nice :)

This one for example:
https://www.gelderlander.nl/video/productie/brandweer-redt-hondje-maya-van-onder-stalvloer-330138

On Chromium I have to disable the extension to make the video work.
Disabling the extension on Firefox has no effect.

**Comment by M1Aston** [comment]
Unrelated to all those newspapers, but the same problem occurs here:
https://www.gld.nl/nieuws/7769556/verslaggever-scheldt-presentator-live-op-radio-uit-dit-is-not-done

Extension enabled: cookie message disappears, but the audio player\fragment doesn't show up at all.

**Comment by OhMyGuus** [comment]
Thanks for the  examples 👍 
It seems to be an issue with websites from DPG media & the rule to block wrapperMessagingWithoutDetection.js 
I have no idea what websites are using wrapperMessagingWithoutDetection.js to show a cookie pop-up (at the moment so will add all missing dpg media websites to the exclude list.

**Comment by M1Aston** [comment]
Well, it does an awful lot better than before. I have seen both Dutch and Belgian sites where the current implementation allows for normal operation\video playback where there used to be problems.

Example:
This website wasn't reported, always had video problems with IDCACookies, but not any more.
https://www.autoweek.nl
