### ISSUE TITLE
[REQ] Website request: https://www.dekamarkt.nl/

### ISSUE THREAD

**Issue by M1Aston** [OhMyGuus/I-Dont-Care-About-Cookies#48]
**Website URL(s)**
https://www.dekamarkt.nl/

**Browser**
[ ] Firefox

**Extension version**
V1.0.0

Vertical scrollbar invisible\disabled.

**Comment by M1Aston** [comment]
Looks like the same cookie and the same problem:
https://www.dirk.nl/

**Comment by OhMyGuus** [comment]
Thanks for the report 👍 will be supported in next update
