### ISSUE TITLE
Chrome Web Store release

### ISSUE THREAD

**Issue by Veriiix** [OhMyGuus/I-Dont-Care-About-Cookies#50]
I found this extension (https://chrome.google.com/webstore/detail/i-still-dont-care-about-c/edibdbjcniadpccecjdfdjjppcpchdlm) on the webstore. Is this the official version and when will it be added to the installation guide?

Edit by @OhMyGuus:
[Firefox browser add-ons](https://addons.mozilla.org/en-US/firefox/addon/istilldontcareaboutcookies/
)
[Chrome Web Store](https://chrome.google.com/webstore/detail/i-still-dont-care-about-c/edibdbjcniadpccecjdfdjjppcpchdlm)
 _(The chrome webstore version is still outdated to v1.0.0 but will be updates soon to v1.0.3 (with the fixes on the store page after review))_

**Comment by OhMyGuus** [comment]
That is indeed the official one, it just got passed the review 😁
Will ofcourse add it to the installation guide soon

**Comment by alfredonodo** [comment]
What about Firefox add-ons?

**Comment by OhMyGuus** [comment]
> What about Firefox add-ons?

V1.0.3 is currently under review for Firefox add-ons & chrome webstore will create a release & a announcement when it is live.

**Comment by OhMyGuus** [comment]
[Firefox browser add-ons](https://addons.mozilla.org/en-US/firefox/addon/istilldontcareaboutcookies/
)
[Chrome Web Store](https://chrome.google.com/webstore/detail/i-still-dont-care-about-c/edibdbjcniadpccecjdfdjjppcpchdlm)
 _(The chrome webstore version is still outdated to v1.0.0 but will be updates soon to v1.0.3 (with the fixes on the store page after review))_

**Comment by luckman212** [comment]
Anyone know when the new release will go live on the Chrome store? It's been 9 days now and 1.0.0 is still showing up there.

**Comment by nicolaasjan** [comment]
> > Anyone know when the new release will go live on the Chrome store? It's been 9 days now and 1.0.0 is still showing up there.
> 
> After V1.0.0 got released I through maybe I can edit the description of the store page without a long review. Sadly I was wrong the review of that simple edit (not even in the package just the description) took 8 days and just got "reviewed" today. Now I have uploaded the correct v1.0.4 and it is back to the waiting game I can't tell you when it goes live sadly I only know the initial V1.0.0 took 3 days to review and a description edit took 8 days to review so yeah disappointed
> 
> --edit: Oh and something I forgot to mention as well after u submitted for review u can't cancel it ---

Couldn't you host the packed `.crx` on GitHub under Releases → Assets  (instead of `
IDCAC-chrome.zip`) ?
Example [here](https://github.com/NeverDecaf/chromium-web-store/releases).

Would be easier to install. 🙂

**Comment by OhMyGuus** [comment]
> > > Anyone know when the new release will go live on the Chrome store? It's been 9 days now and 1.0.0 is still showing up there.
> > 
> > 
> > After V1.0.0 got released I through maybe I can edit the description of the store page without a long review. Sadly I was wrong the review of that simple edit (not even in the package just the description) took 8 days and just got "reviewed" today. Now I have uploaded the correct v1.0.4 and it is back to the waiting game I can't tell you when it goes live sadly I only know the initial V1.0.0 took 3 days to review and a description edit took 8 days to review so yeah disappointed
> > --edit: Oh and something I forgot to mention as well after u submitted for review u can't cancel it ---
> 
> Couldn't you host the packed `.crx` on GitHub under Releases → Assets (instead of ` IDCAC-chrome.zip`) ? Example [here](https://github.com/NeverDecaf/chromium-web-store/releases).
> 
> Would be easier to install. 🙂

Thanks a lot for the advice, that is indeed way! It even replaces/updates the old version if u downloaded it from the webstore 👍

**Comment by nicolaasjan** [comment]
> Thanks a lot for the advice, that is indeed way! It even replaces/updates the old version if u downloaded it from the webstore +1

👍️
I just tried this new one, but it didn't show the green check mark on the badge yet, whereas the one built by me yesterday from `./tree/master/src` did.
[I-Still-Dont-Care-About-Cookies 1.0.4.4.crx.zip](https://github.com/OhMyGuus/I-Dont-Care-About-Cookies/files/9738367/I-Still-Dont-Care-About-Cookies.1.0.4.4.crx.zip)

**Comment by OhMyGuus** [comment]
> > Thanks a lot for the advice, that is indeed way! It even replaces/updates the old version if u downloaded it from the webstore +1
> 
> 👍️ I just tried this new one, but it didn't show the green check mark on the badge yet, whereas the one built by me yesterday from `./tree/master/src` did. [I-Still-Dont-Care-About-Cookies 1.0.4.4.crx.zip](https://github.com/OhMyGuus/I-Dont-Care-About-Cookies/files/9738367/I-Still-Dont-Care-About-Cookies.1.0.4.4.crx.zip)
> 
> **[Edit]** That must be because I used `manifest_v2.json` (?). So obviously Manifest V3 has some shortcomings. :(

aaaaaaaaaaaaaaaaaaaaaaaa....... I tested it by mistake on manifest v2 as well 😠  so now 1.0.4 most likely isn't working correctly anymore for manifest v3 and I can't cancel the webstore process on chrome 😢. 
(sooo 1.0.4 is delayed again for the chrome webstore because of a stupid mistake 😠😢😢)

**Comment by OhMyGuus** [comment]
The update to chrome was fast this time 😄 I uploaded 1.0.5 yesterday and it has been published now!
