### ISSUE TITLE
[REQ] Website request: https://yellow.systems

### ISSUE THREAD

**Issue by lvzhenbo** [OhMyGuus/I-Dont-Care-About-Cookies#53]
**Website URL(s)**
- [https://yellow.systems/](https://yellow.systems/)

**Browser**
[ ] Firefox
[x] Chrome

**Extension version**
V1.0.2

**Comment by OhMyGuus** [comment]
Thanks for the report

-- Info for me --
localstorage -> isCookiesNotificationHidden true
css selector > styles_cookiesNotification__hd6RB

**Comment by lvzhenbo** [comment]
Yes, both of them can solve the problem

**Comment by OhMyGuus** [comment]
Will be supported in the next update thanks for the request 👍
