### ISSUE TITLE
Mirror (or duplicate) on the Chrome webstore

### ISSUE THREAD

**Issue by TheOGUmar** [OhMyGuus/I-Dont-Care-About-Cookies#55]
@OhMyGuus I see that there is [another extension](https://chrome.google.com/webstore/detail/still-dont-care-about-coo/fmmjjgjhblhocbmigepoobidbbcknjkf) called by the same name published by another user on the webstore although i'm not sure if it's a duplicate or a mirror, it links to a [website](https://www.stilldontcareaboutcookies.com/) that seems like the official page... do you own the website?

**Comment by TheOGUmar** [comment]
From his website it seems he's taking a 1 euro fee for the extension

**Comment by OhMyGuus** [comment]
That is not our extension, its another fork (that kind of decided on the same name for some reason) that doesn't even work at the moment. (It doesn't contain the rules so yeah..) 
But I already made a announcement about it but will pin this issue for now as well 👍 
 
If you are looking for our extension the webstore. 
- [Firefox browser add-ons](https://addons.mozilla.org/en-US/firefox/addon/istilldontcareaboutcookies/
)
- [Chrome Web Store](https://chrome.google.com/webstore/detail/i-still-dont-care-about-c/edibdbjcniadpccecjdfdjjppcpchdlm)
