### ISSUE TITLE
[REQ] Website request: https://www.schobuell-wetter.de/

### ISSUE THREAD

**Issue by gwak64** [OhMyGuus/I-Dont-Care-About-Cookies#56]
**Website URL(s)**
- Example.com

**Browser**
[ ] Firefox
[x] Chrome

**Extension version**
V1.0.0

**Comment by appeasementPolitik** [comment]
Can be fixed by removing `div#consent.light.backdrop` or by setting the cookie 

`zp_consent: "%7B%22zp_consent_all%22%3Afalse%2C%22zp_consent_yt%22%3Afalse%2C%22zp_consent_gmaps%22%3Afalse%2C%22zp_consent_osmaps%22%3Afalse%2C%22zp_consent_zp%22%3Atrue%7D"`

**Comment by OhMyGuus** [comment]
> Can be fixed in Firefox by removing `div#consent.light.backdrop` or by setting the cookie
> 
> `zp_consent: "%7B%22zp_consent_all%22%3Afalse%2C%22zp_consent_yt%22%3Afalse%2C%22zp_consent_gmaps%22%3Afalse%2C%22zp_consent_osmaps%22%3Afalse%2C%22zp_consent_zp%22%3Atrue%7D"`

Thanks a lot 😄

**Comment by OhMyGuus** [comment]
Will be supported in the next update thanks for the request 👍
