### ISSUE TITLE
[REQ] Website request: https://www.prosciutteriasandaniele.it

### ISSUE THREAD

**Issue by Darkmagister** [OhMyGuus/I-Dont-Care-About-Cookies#59]
**Website URL(s)**
- [https://www.prosciutteriasandaniele.it](https://www.prosciutteriasandaniele.it)

**Browser**
[x] Firefox
[ ] Chrome

**Extension version**
V1.0.3

there is still a div with class page_hider that block the page

**Comment by OhMyGuus** [comment]
Will be supported in the next update thanks for the request 👍
