### ISSUE TITLE
[REQ] Website request: https://voebb.onleihe.de/

### ISSUE THREAD

**Issue by dayt47** [OhMyGuus/I-Dont-Care-About-Cookies#61]
**Website URL(s)**
- https://voebb.onleihe.de/

**Browser**
[ ] Firefox
[x] Chrome

**Extension version**
V1.0.0

**Comment by appeasementPolitik** [comment]
Let me try one with my limited web knowledge

To hide cookie banner and make website functional for as far as I could tell:

Remove the element `div#cookiePopup.modal.fade.show`
Remove the element `div.modal-backdrop.fade.show`
Remove `overflow: hidden` in `element` class in `body.d-flex.flex-column.h-100.modal-open`

Alternatively:

Clicking the grey consent button `button.btn.btn-light.privacyAcceptChoice.fw-bold` sets the cookie `onleiheTracking: false`. Setting the cookie also allows access.

**Comment by OhMyGuus** [comment]
> To hide cookie banner and make website functional for as far as I could tell on Firefox:
> 
> Remove the element `div.modal-backdrop.fade.show` Remove `overflow: hidden` in `element` class in `body.d-flex.flex-column.h-100.modal-open`
> 
> Alternatively:
> 
> Clicking the grey consent button `button.btn.btn-light.privacyAcceptChoice.fw-bold` sets the cookie `onleiheTracking: false`. Setting the cookie also allows access.

Thanks a lot 😄 used the cookie for this website (since the modal could be used for other things)

**Comment by OhMyGuus** [comment]
Will be supported in the next update thanks for the request 👍
