### ISSUE TITLE
[REQ] Site request: https://healthmate.withings.com (Scrolling blocked, Unfortunately login required)

### ISSUE THREAD

**Issue by helptiger** [OhMyGuus/I-Dont-Care-About-Cookies#62]
**Website URL(s)**
- https://healthmate.withings.com

**Browser**
[x] Firefox
[ ] Chrome

**Extension version**
V1.0.3

Scrolling is blocked
Login is required for testing

**Comment by OhMyGuus** [comment]
Will be supported in the next update thanks for the report and thanks appeasementPolitik for the assistance.
