### ISSUE TITLE
[REQ] Website request: https://www.thekey.academy

### ISSUE THREAD

**Issue by CreeTar** [OhMyGuus/I-Dont-Care-About-Cookies#63]
**Website URL(s)**
- https://www.thekey.academy

**Browser**
[ ] Firefox
[x] Chrome

**Extension version**
V1.0.0

**Comment by appeasementPolitik** [comment]
Css to remove on Firefox: `div.p-dialog-mask.p-component-overlay.p-component-overlay-enter.p-dialog-visible.p-dialog-draggable.p-dialog-resizable.p-dialog-bottom` 

Alternatively, cookie can be set for least options:

`tk-optout: "true"`

**Comment by OhMyGuus** [comment]
Will be supported in the next update thanks for the report and thanks appeasementPolitik for the assistance.
