### ISSUE TITLE
[FEATURE] Report a website without Github login

### ISSUE THREAD

**Issue by OhMyGuus** [OhMyGuus/I-Dont-Care-About-Cookies#71]
Add a way to report a website without a Github account.

**Comment by appeasementPolitik** [comment]
Maybe something like a Github bot or user that can create an issue in the right format after being given an URL and info about what browser is used?

I found this which can help:

https://ez34.net/2016/12/publish-anonymous-issues-on-github.html

Of course we do want to use something else than Google Forms, haha

**Comment by OhMyGuus** [comment]
> Maybe something like a Github bot or user that can create an issue in the right format after being given an URL and info about what browser is used?
> 
> I found this which can help:
> 
> https://ez34.net/2016/12/publish-anonymous-issues-on-github.html
> 
> Of course we do want to use something else than Google Forms, haha

Yeah that's exacty what I was thinking about as well, a simple api that just creates a Github issue. 
https://docs.github.com/en/rest/issues/issues#create-an-issue
