### ISSUE TITLE
[REQ] Website request: https://ludigoodies.com/

### ISSUE THREAD

**Issue by STVGecko** [OhMyGuus/I-Dont-Care-About-Cookies#76]
**Website URL(s)**

https://ludigoodies.com/

- Example.com

**Browser**
[x] Firefox
[] Chrome

**Extension version**
V1.0.3

**Comment by appeasementPolitik** [comment]
localstorage: `_cookieAllowed:"true"`
element to hide: `uk-section.uk-section-xsmall.uk-section-primary.uk-position-bottom.uk-position-fixed.uk-position-z-index`
