### ISSUE TITLE
[Extension: Firefox] Name in German Firefox Extension Store

### ISSUE THREAD

**Issue by hofq** [OhMyGuus/I-Dont-Care-About-Cookies#86]
In the Firefox Store used in the German Language, the Extension is still called I don't care about Cookies.

![grafik](https://user-images.githubusercontent.com/54744977/194176991-aeb4cd2d-305b-4703-af67-69120dc664dc.png)
https://addons.mozilla.org/de/firefox/addon/istilldontcareaboutcookies/

Since it was rebranded, it would be nice if you could edjust the name for the Other Languages in the Extension Store. 

Thanks!

**Comment by OhMyGuus** [comment]
Thanks 👍 
Will upload a new version tomorrow, with the correct names. (It was still the old ones for NL, DE)

**Comment by ikanakova** [comment]
@OhMyGuus The old one is also for e.g. CZ, SK.

**Comment by OhMyGuus** [comment]
It was indeed wrong on all languages, found now the way to do it. I first thought it was a mistake in the localize files, but operantly there is a localization button in the Firefox store as well. Thanks for the report and saying it was wrong on other languages as well 😃 

But it is fixed now :)
