### ISSUE TITLE
Update resets whitelist

### ISSUE THREAD

**Issue by d4k0** [OhMyGuus/I-Dont-Care-About-Cookies#93]
Hi,

I just got the update to 1.0.4. Unfortunately, the whitelist got reset:

![firefox_2022-10-07_02-17-24](https://user-images.githubusercontent.com/10982825/194441127-818f2665-7e43-4ccc-89b9-85f2cee94c79.png)

I never had this problem with the original add-on, so maybe a bug was introduced in the last version. I'm using Firefox 105.0.2.

**Comment by OhMyGuus** [comment]
Thanks, I indeed forgot to put this in the changelogs. I reworked the settings so it is a one time reset.

**Comment by d4k0** [comment]
Thanks for the quick answer!
