### ISSUE TITLE
[REQ] Website request: maisonstandards.com

### ISSUE THREAD

**Issue by nam1962** [OhMyGuus/I-Dont-Care-About-Cookies#96]
**Website URL(s)**

[- maisonstandards.com](https://www.maisonstandards.com/fr/content/1-livraison-retour)

**Browser**
[X ] Firefox
firefox-105.0.3-1

**Extension version**
V1.0.0

**Comment by 2345554** [comment]
> **Website URL(s)**
> 
> 
> 
> [- maisonstandards.com](https://www.maisonstandards.com/fr/content/1-livraison-retour)
> 
> 
> 
> **Browser**
> 
> [X ] Firefox
> 
> firefox-105.0.3-1
> 
> 
> 
> **Extension version**
> 
> V1.0.0
> 
>
